### ISSUE TITLE
기초 개념 설명 및 전공 소개 문서 작성

### ISSUE THREAD

**Issue by rlaisqls** [dsmhs/dsm-freshman-guide#1]
### 제안

신입생의 수월한 전공 공부 입문을 위해선 가이드에 "**각 전공의 개념을 이해하기 위한 기초 지식**"에 대한 설명을 포함하는 것이 바람직한 것 같다는 생각이 들었습니다.

각 전공의 심화 단계까지는 아니더라도
- 시작하기 분류에는
  - 웹, 네트워크란?
  - 클라이언트와 서버 개념 
  - 기본적인 네트워크 개념 (도메인, HTTP/S, TCP, IP)
 
- 각 전공 분류에는
  - 각 전공의 개요 및 특징 (분야 설명회 때 다룰만 한 내용들)

이러한 내용을 간략하게 설명하는 문서를 추가하면 어떨까요?

### 참고

이 시리즈의 내용에서 영감받았습니당.

https://velog.io/@entrydsm/series/신입생을-위한-EntryDSM-커리큘럼

![image](https://github.com/dsmhs/dsm-freshman-guide/assets/81006587/408ca7b3-ac42-4038-a001-736d2fd63fdd)

**Comment by jeongho1209** [comment]
좋습니다! 🥹
